import { StyleSheet, Platform } from 'react-native';
import { COLOURS } from '@shared/constants/colours';

export const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'flex-end',
    },
    keyboardWrapper: {
        flex: 1,
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: COLOURS.white,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: Platform.OS === 'ios' ? 40 : 24,
        maxHeight: '96%',
        width: '100%',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start', 
        marginBottom: 24,
    },
    title: {
        fontSize: 24,
        fontFamily: 'Wals-Medium', 
        color: COLOURS.Black,
        marginTop: 20,
    },
    scrollContent: {
        paddingBottom: 20,
    },
    tagsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 16,
        alignItems: 'center',
    },
    tagBadge: {
        backgroundColor: COLOURS.Plum50,
        borderRadius: 6,
        padding: 6,
    },
    tagText: {
        color: COLOURS.Plum,
        fontFamily: 'Wals-Regular', 
        fontSize: 14,
    },
    closeIcon: {
        fontSize: 20, 
        fontFamily: 'Wals-Medium',
        color: COLOURS.Black,
        marginTop: 2, 
    },
    addTagActiveWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        width: '100%',
        marginTop: 4,
    },
    tagInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLOURS.Blue20,
        borderRadius: 4,
        paddingHorizontal: 8,
        height: 36,
        width: '60%',
    },
    hashtagPrefix: {
        fontFamily: 'Wals-Regular',
        color: COLOURS.Black,
        fontSize: 14,
        marginRight: 2,
    },
    inlineTagInput: {
        flex: 1,
        height: '100%',
        fontFamily: 'Wals-Regular',
        fontSize: 14,
        color: COLOURS.Black,
        padding: 0,
    },
    circleIconButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        borderWidth: 1.2,
        borderColor: COLOURS.Plum,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: COLOURS.white,
    },
    circleIconButtonText: {
        fontSize: 18,
        fontFamily: 'Wals-Regular', 
        color: COLOURS.Black,
        lineHeight: 20,
    },
    inputLabel: {
        fontSize: 14,
        fontFamily: 'Wals-Medium',
        color: COLOURS.Black,
        marginBottom: 8,
    },
    linkRow: {
        flexDirection: 'row',
        alignItems: 'center', 
        gap: 8,
        marginBottom: 12,
    },
    linkInputWrapper: {
        flex: 1,
    },
    linkActionButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: 8, 
    },
    imagePreviewContainer: {
        width: '100%',
        height: 200,
        borderRadius: 16,
        overflow: 'hidden',
        position: 'relative',
        marginBottom: 12,
    },
    imagePreview: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    deleteImageBtn: {
        position: 'absolute',
        top: 12,
        right: 12,
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: COLOURS.white,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    scrollWrapper: {
        flexShrink: 1,
        position: 'relative',
    },
    customScrollTrack: {
        position: 'absolute',
        right: -10, 
        top: 10,
        bottom: 10,
        width: 3,
        backgroundColor: 'transparent',
        borderRadius: 10,
    },
    customScrollThumb: {
        width: '100%',
        borderRadius: 10,
        backgroundColor: COLOURS.Plum,
    },
    bottomActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        paddingTop: 16,
        gap: 12,
    },
    publishButton: {
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 24,
        height: 40,
        width: 'auto',
        flex: 0,
    },
    publishButtonText: {
        fontFamily: 'Wals-Medium',
        fontSize: 14,
    },
});